[settings]
minimum_release_age = "7d"

[tools]
python = "prefix:3.13"
php = "8.3"
node = "26"
go = "latest"
pnpm = "latest"
"npm:@jetbrains/junie-cli" = "latest"
"npm:corepack" = "latest"
"npm:difit" = "latest"
claude = "latest"
